include ../Makefile.mm.inc 

OBJECTS = mm.o check.o prthead.o gendat.o prtspeed.o mxm.o \
          state.o  cclock.o

EXEC    = x.mm

${EXEC}: ${OBJECTS}
	@echo
	${LD} ${LDFLAGS} -o ${EXEC} ${OBJECTS} ${LIBS}

.SUFFIXES: .c .o
.c.o    :
	@echo
	${CC} ${CFLAGS} -c $<

clean   :
	/bin/rm -f ${OBJECTS} *.oo

veryclean:
	/bin/rm -f ${OBJECTS} *.oo ${EXEC}
